services:
  web:
    build: .
    image: vehicle-fe:latest
    container_name: vehicle-fe
    ports:
      - "80:80"        # kalau port 80 sudah dipakai, ganti ke "8081:80"
    restart: unless-stopped
